/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ComplianceLog {
  export type AttestationStruct = {
    sessionId: string;
    bugCategory: string;
    filePath: string;
    line: BigNumberish;
    errorMessage: string;
    fixDescription: string;
    testBeforePassed: boolean;
    testAfterPassed: boolean;
    commitSha: string;
    timestamp: BigNumberish;
    agent: AddressLike;
  };

  export type AttestationStructOutput = [
    sessionId: string,
    bugCategory: string,
    filePath: string,
    line: bigint,
    errorMessage: string,
    fixDescription: string,
    testBeforePassed: boolean,
    testAfterPassed: boolean,
    commitSha: string,
    timestamp: bigint,
    agent: string
  ] & {
    sessionId: string;
    bugCategory: string;
    filePath: string;
    line: bigint;
    errorMessage: string;
    fixDescription: string;
    testBeforePassed: boolean;
    testAfterPassed: boolean;
    commitSha: string;
    timestamp: bigint;
    agent: string;
  };
}

export interface ComplianceLogInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attestationCount"
      | "attestations"
      | "authorizedAgent"
      | "getAttestation"
      | "getSessionAttestationCount"
      | "getSessionAttestationIds"
      | "recordAttestation"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AttestationRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "attestationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "attestations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedAgent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSessionAttestationCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSessionAttestationIds",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordAttestation",
    values: [
      string,
      string,
      string,
      BigNumberish,
      string,
      string,
      boolean,
      boolean,
      string
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "attestationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSessionAttestationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSessionAttestationIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordAttestation",
    data: BytesLike
  ): Result;
}

export namespace AttestationRecordedEvent {
  export type InputTuple = [
    id: BigNumberish,
    sessionId: string,
    bugCategory: string,
    filePath: string,
    commitSha: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    sessionId: string,
    bugCategory: string,
    filePath: string,
    commitSha: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    sessionId: string;
    bugCategory: string;
    filePath: string;
    commitSha: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ComplianceLog extends BaseContract {
  connect(runner?: ContractRunner | null): ComplianceLog;
  waitForDeployment(): Promise<this>;

  interface: ComplianceLogInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attestationCount: TypedContractMethod<[], [bigint], "view">;

  attestations: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        string,
        string,
        boolean,
        boolean,
        string,
        bigint,
        string
      ] & {
        sessionId: string;
        bugCategory: string;
        filePath: string;
        line: bigint;
        errorMessage: string;
        fixDescription: string;
        testBeforePassed: boolean;
        testAfterPassed: boolean;
        commitSha: string;
        timestamp: bigint;
        agent: string;
      }
    ],
    "view"
  >;

  authorizedAgent: TypedContractMethod<[], [string], "view">;

  getAttestation: TypedContractMethod<
    [_id: BigNumberish],
    [ComplianceLog.AttestationStructOutput],
    "view"
  >;

  getSessionAttestationCount: TypedContractMethod<
    [_sessionId: string],
    [bigint],
    "view"
  >;

  getSessionAttestationIds: TypedContractMethod<
    [_sessionId: string],
    [bigint[]],
    "view"
  >;

  recordAttestation: TypedContractMethod<
    [
      _sessionId: string,
      _bugCategory: string,
      _filePath: string,
      _line: BigNumberish,
      _errorMessage: string,
      _fixDescription: string,
      _testBeforePassed: boolean,
      _testAfterPassed: boolean,
      _commitSha: string
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attestationCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "attestations"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        string,
        string,
        boolean,
        boolean,
        string,
        bigint,
        string
      ] & {
        sessionId: string;
        bugCategory: string;
        filePath: string;
        line: bigint;
        errorMessage: string;
        fixDescription: string;
        testBeforePassed: boolean;
        testAfterPassed: boolean;
        commitSha: string;
        timestamp: bigint;
        agent: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "authorizedAgent"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [ComplianceLog.AttestationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSessionAttestationCount"
  ): TypedContractMethod<[_sessionId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSessionAttestationIds"
  ): TypedContractMethod<[_sessionId: string], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "recordAttestation"
  ): TypedContractMethod<
    [
      _sessionId: string,
      _bugCategory: string,
      _filePath: string,
      _line: BigNumberish,
      _errorMessage: string,
      _fixDescription: string,
      _testBeforePassed: boolean,
      _testAfterPassed: boolean,
      _commitSha: string
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "AttestationRecorded"
  ): TypedContractEvent<
    AttestationRecordedEvent.InputTuple,
    AttestationRecordedEvent.OutputTuple,
    AttestationRecordedEvent.OutputObject
  >;

  filters: {
    "AttestationRecorded(uint256,string,string,string,string,uint256)": TypedContractEvent<
      AttestationRecordedEvent.InputTuple,
      AttestationRecordedEvent.OutputTuple,
      AttestationRecordedEvent.OutputObject
    >;
    AttestationRecorded: TypedContractEvent<
      AttestationRecordedEvent.InputTuple,
      AttestationRecordedEvent.OutputTuple,
      AttestationRecordedEvent.OutputObject
    >;
  };
}
