/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
 
export type { ComplianceLog } from "./ComplianceLog";
export * as factories from "./factories";
export { ComplianceLog__factory } from "./factories/ComplianceLog__factory";
